apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: aws-account
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/aws-account
    meta.crossplane.io/description: Vends AWS Organizations accounts, OU placement, and ProviderConfigs.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-organizations
    version: ">=v2.3.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
