apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-account
spec:
  package: ghcr.io/hops-ops/aws-account:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}

---

apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-aws-accountrender
spec:
  package: ghcr.io/hops-ops/aws-account_render:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}
